# 1. Database Connection (The Phone Number)
spring.datasource.url=jdbc:postgresql://localhost:5432/pos_db
spring.datasource.username=postgres
# Replace 'yourpassword' with the password you used in the terminal
spring.datasource.password=Saurabh@52

# 2. SQL Persistence (The Bridge)
# 'update' means Spring will automatically create/update your tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Application Name
spring.application.name=terminal
