# 1. Database Connection (The Phone Number)
spring.datasource.url=jdbc:postgresql://localhost:5432/pos_db
spring.datasource.username=postgres
# Replace 'yourpassword' with the password you used in the terminal
spring.datasource.password=Saurabh@52

# 2. SQL Persistence (The Bridge)
# 'update' means Spring will automatically create/update your tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Application Name
spring.application.name=terminal


# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saurabh52bansal@gmail.com
# Paste the 16-character code here (no spaces)
spring.mail.password=pjig vknj zajo llyb

# Mail Protocol Settings
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000